import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import api from '../services/api';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Separator } from '../components/ui/Separator';
import { 
  MessageCircle, 
  Download, 
  CheckCircle, 
  ChevronLeft, 
  Loader2, 
  Printer,
  Calendar,
  User,
  Hash,
  ShoppingBag
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { formatCurrency, formatDate, cn } from '@/lib/utils';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const InvoicePreviewPage = () => {
  const { id } = useParams();
  const { user: authUser } = useAuth();
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [markingPaid, setMarkingPaid] = useState(false);

  useEffect(() => {
    fetchInvoice();
  }, [id]);

  const fetchInvoice = async () => {
    try {
      const res = await api.get(`/invoice/${id}`);
      setInvoice(res.data);
    } catch (err) {
      console.error('Failed to fetch invoice', err);
    } finally {
      setLoading(false);
    }
  };

  const markAsPaid = async () => {
    setMarkingPaid(true);
    try {
      await api.put(`/invoice/${id}/pay`);
      fetchInvoice();
    } catch (err) {
      alert('Failed to update status');
    } finally {
      setMarkingPaid(false);
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Brand Header Background
    doc.setFillColor(40, 120, 255);
    doc.rect(0, 0, 210, 40, 'F');
    
    // Brand Name
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(invoice.user.shopName.toUpperCase(), 20, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Tax Invoice / Bill of Supply', 20, 32);
    
    // Invoice Details (Top Right)
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`INVOICE: #${invoice.id.slice(0, 8).toUpperCase()}`, 190, 20, { align: 'right' });
    doc.text(`DATE: ${new Date(invoice.createdAt).toLocaleDateString()}`, 190, 26, { align: 'right' });
    doc.text(`STATUS: ${invoice.status.toUpperCase()}`, 190, 32, { align: 'right' });
    
    // Billing Info
    doc.setTextColor(100);
    doc.setFontSize(9);
    doc.text('BILL TO:', 20, 55);
    doc.text('FROM:', 130, 55);
    
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(invoice.customer.name, 20, 65);
    doc.text(invoice.user.name, 130, 65);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    doc.text(`Phone: ${invoice.customer.phone}`, 20, 72);
    doc.text(invoice.user.shopName, 130, 72);
    doc.text(invoice.user.email, 130, 77);
    doc.text(`Tel: ${invoice.user.phone}`, 130, 82);
    
    // Items Table
    const tableData = invoice.items.map((item, i) => [
      i + 1,
      item.name,
      `INR ${item.price.toFixed(2)}`,
      item.quantity.toString(),
      `INR ${(item.price * item.quantity).toFixed(2)}`
    ]);
    
    doc.autoTable({
      startY: 95,
      head: [['#', 'Item Description', 'Price', 'Qty', 'Total']],
      body: tableData,
      theme: 'striped',
      headStyles: { 
        fillColor: [40, 120, 255],
        textColor: 255,
        fontSize: 10,
        fontStyle: 'bold',
        halign: 'center'
      },
      columnStyles: { 
        0: { halign: 'center', cellWidth: 10 },
        2: { halign: 'right' },
        3: { halign: 'center' },
        4: { halign: 'right' }
      },
      styles: { fontSize: 9, cellPadding: 5 }
    });
    
    // Summary
    const finalY = doc.lastAutoTable.finalY + 15;
    
    // Terms
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('TERMS & CONDITIONS', 20, finalY);
    doc.text('1. Payment is due within 7 days.', 20, finalY + 5);
    doc.text('2. Please contact us for any discrepancies.', 20, finalY + 10);
    
    // Totals
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('Subtotal:', 140, finalY);
    doc.text(`INR ${invoice.totalAmount.toFixed(2)}`, 190, finalY, { align: 'right' });
    
    doc.setFontSize(18);
    doc.setTextColor(40, 120, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('Total Amount:', 140, finalY + 12);
    doc.text(`INR ${invoice.totalAmount.toFixed(2)}`, 190, finalY + 12, { align: 'right' });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(180);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by BillFlow • Smart Billing for Small Business', 105, 285, { align: 'center' });
    
    return doc;
  };

  const downloadPDF = () => {
    const doc = generatePDF();
    doc.save(`invoice_${invoice.id.slice(0, 8)}.pdf`);
  };

  const shareInvoice = async () => {
    const doc = generatePDF();
    const blob = doc.output('blob');
    const fileName = `invoice_${invoice.id.slice(0, 8)}.pdf`;
    const file = new File([blob], fileName, { type: 'application/pdf' });

    // Check if sharing files is supported (mostly mobile)
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          files: [file],
          title: `Invoice #${invoice.id.slice(0, 8)}`,
          text: `Invoice from ${invoice.user.shopName}`
        });
      } catch (err) {
        if (err.name !== 'AbortError') handleFallbackShare();
      }
    } else {
      handleFallbackShare();
    }
  };

  const handleFallbackShare = () => {
    const text = encodeURIComponent(
      `Hello ${invoice.customer.name},\n\nYour invoice from *${invoice.user.shopName}* is ready.\n\n*Amount:* ${formatCurrency(invoice.totalAmount)}\n*Status:* ${invoice.status.toUpperCase()}\n\nView details here: ${window.location.href}`
    );
    window.open(`https://wa.me/${invoice.customer.phone}?text=${text}`, '_blank');
  };

  if (loading) return (
    <div className="h-full flex flex-col items-center justify-center p-20 gap-4">
       <Loader2 className="w-10 h-10 animate-spin text-brand-600" />
       <p className="text-slate-500 font-medium">Preparing your bill preview...</p>
    </div>
  );

  if (!invoice) return <div className="p-8 text-center text-red-500">Invoice not found.</div>;

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20 animate-in zoom-in-95 duration-500">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .print-area, .print-area * { visibility: visible; }
          .print-area { position: absolute; left: 0; top: 0; width: 100%; padding: 0 !important; margin: 0 !important; }
          .no-print { display: none !important; }
          aside, header { display: none !important; }
          main { padding: 0 !important; margin: 0 !important; overflow: visible !important; }
          .rounded-3xl { border-radius: 0 !important; }
          .shadow-2xl { box-shadow: none !important; }
          .bg-brand-600 { -webkit-print-color-adjust: exact; background-color: #2878ff !important; }
          @page { margin: 1cm; size: A4; }
        }
      `}</style>
      
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 border-b border-slate-200 pb-6 no-print">
         <div>
            {authUser && (
               <Link to="/invoices">
                  <Button variant="ghost" className="gap-2 text-slate-500 hover:text-slate-900">
                     <ChevronLeft className="w-4 h-4" />
                     View All
                  </Button>
               </Link>
            )}
            {!authUser && (
               <div className="flex items-center gap-2 text-slate-400 font-medium px-4">
                  <ShoppingBag className="w-5 h-5" />
                  <span>BillFlow Guest View</span>
               </div>
            )}
         </div>

         <div className="flex items-center gap-2">
            <Button variant="outline" className="gap-2 rounded-xl" onClick={downloadPDF}>
               <Download className="w-4 h-4" />
               PDF
            </Button>
            <Button variant="outline" className="gap-2 rounded-xl" onClick={() => window.print()}>
               <Printer className="w-4 h-4" />
               Print
            </Button>
            {authUser && (
               <Button className="bg-[#25D366] hover:bg-[#128C7E] text-white gap-2 rounded-xl shadow-lg border-none" onClick={shareInvoice}>
                  <MessageCircle className="w-5 h-5 fill-current" />
                  WhatsApp Share
               </Button>
            )}
         </div>
      </div>

      <Card className="shadow-2xl shadow-slate-200 border-none overflow-hidden print-area bg-white rounded-3xl">
        <CardContent className="p-0">
          {/* Bill Header */}
          <div className="bg-brand-600 p-8 text-white flex flex-col sm:flex-row items-start justify-between gap-6">
             <div className="space-y-4">
                <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur-md flex items-center justify-center border border-white/20">
                   <ShoppingBag className="w-10 h-10" />
                </div>
                <div>
                   <h2 className="text-3xl font-black uppercase tracking-tighter">{invoice.user.shopName}</h2>
                   <p className="text-brand-100 font-medium">Tax Invoice / Bill of Supply</p>
                </div>
             </div>
             <div className="text-right space-y-1">
                <Badge className="bg-white text-brand-600 border-white hover:bg-white px-4 py-1.5 text-sm mb-4">
                   {invoice.status.toUpperCase()}
                </Badge>
                <p className="text-brand-200 flex items-center justify-end gap-2 text-sm italic">
                   <Hash className="w-4 h-4" />
                   #{invoice.id.toUpperCase()}
                </p>
                <p className="text-brand-200 flex items-center justify-end gap-2 text-sm italic">
                   <Calendar className="w-4 h-4" />
                   {formatDate(invoice.createdAt)}
                </p>
             </div>
          </div>

          <div className="p-8 md:p-12 space-y-12">
             {/* Billing Addresses */}
             <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                <div className="space-y-4">
                   <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                      <User className="w-4 h-4" />
                      Bill To
                   </h3>
                   <div>
                      <p className="text-2xl font-black text-slate-900">{invoice.customer.name}</p>
                      <p className="text-slate-500 font-medium flex items-center gap-2 mt-1 italic">
                        <MessageCircle className="w-3.5 h-3.5" />
                        {invoice.customer.phone}
                      </p>
                   </div>
                </div>

                <div className="space-y-4 text-left md:text-right">
                   <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest flex items-center justify-start md:justify-end gap-2">
                      <Store className="w-4 h-4 hidden md:block" />
                      From
                   </h3>
                   <div>
                      <p className="text-lg font-bold text-slate-900">{invoice.user.name}</p>
                      <p className="text-slate-500 italic">{invoice.user.shopName}</p>
                      <p className="text-slate-500 text-sm mt-1">{invoice.user.email}</p>
                      <p className="text-slate-500 text-sm">{invoice.user.phone}</p>
                   </div>
                </div>
             </div>

             {/* Items Table */}
             <div className="space-y-4">
                <div className="hidden sm:grid grid-cols-12 gap-4 text-xs font-black text-slate-400 uppercase tracking-widest px-4">
                   <div className="col-span-1 border-r border-slate-100">#</div>
                   <div className="col-span-6 border-r border-slate-100">Description</div>
                   <div className="col-span-2 text-right border-r border-slate-100">Price</div>
                   <div className="col-span-1 text-center border-r border-slate-100">Qty</div>
                   <div className="col-span-2 text-right">Total</div>
                </div>
                <Separator />
                <div className="space-y-4">
                   {invoice.items.map((item, i) => (
                     <div key={item.id} className="grid grid-cols-1 sm:grid-cols-12 gap-4 px-4 items-center">
                        <div className="hidden sm:block col-span-1 text-slate-300 font-mono text-sm">{i + 1}</div>
                        <div className="col-span-12 sm:col-span-6">
                           <p className="font-bold text-slate-900">{item.name}</p>
                           <p className="sm:hidden text-xs text-slate-500">
                             {item.quantity} x {formatCurrency(item.price)}
                           </p>
                        </div>
                        <div className="hidden sm:block col-span-2 text-right text-slate-600 font-medium">{formatCurrency(item.price)}</div>
                        <div className="hidden sm:block col-span-1 text-center text-slate-600 font-medium">{item.quantity}</div>
                        <div className="col-span-12 sm:col-span-2 text-right font-black text-slate-900">
                           {formatCurrency(item.price * item.quantity)}
                        </div>
                     </div>
                   ))}
                </div>
                <Separator />
             </div>

             {/* Summary & Actions */}
             <div className="flex flex-col md:flex-row items-center justify-between gap-12 pt-8">
                <div className="max-w-xs space-y-4">
                   <div className="p-6 rounded-2xl bg-brand-50 border border-brand-100 italic">
                      <p className="text-xs text-brand-600 font-bold uppercase mb-2">Terms & Conditions</p>
                      <p className="text-xs text-brand-700 leading-relaxed italic">
                         Thank you for your business. Please make payments within 7 days.
                         For any queries, please contact us at {invoice.user.phone}.
                      </p>
                   </div>
                </div>

                <div className="w-full md:w-80 space-y-6">
                   <div className="space-y-3">
                      <div className="flex items-center justify-between text-slate-500">
                         <span className="font-medium italic">Subtotal</span>
                         <span className="font-bold">{formatCurrency(invoice.totalAmount)}</span>
                      </div>
                      <div className="flex items-center justify-between text-slate-500">
                         <span className="font-medium italic">Tax (0%)</span>
                         <span>--</span>
                      </div>
                      <Separator />
                      <div className="flex items-center justify-between text-slate-950">
                         <span className="text-xl font-black italic">Amount Due</span>
                         <span className="text-3xl font-black tracking-tighter">{formatCurrency(invoice.totalAmount)}</span>
                      </div>
                   </div>

                   {invoice.status === 'pending' && authUser && (
                     <div className="no-print w-full">
                       <Button className="w-full h-14 rounded-2xl gap-2 font-bold text-lg" onClick={markAsPaid} disabled={markingPaid}>
                          {markingPaid ? (
                             <Loader2 className="w-5 h-5 animate-spin" />
                          ) : (
                             <>
                                <CheckCircle className="w-5 h-5" />
                                Mark as Fully Paid
                             </>
                          )}
                       </Button>
                     </div>
                   )}
                </div>
             </div>
          </div>
          
          <div className="bg-slate-50 p-8 text-center">
             <p className="text-slate-400 text-xs font-medium uppercase tracking-widest italic">Generated by BillFlow • Smart Billing for Small Business</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

// Internal icons helper (can be moved or imported if available)
const Store = ({className}) => <span className={className}><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg></span>;

export default InvoicePreviewPage;
